name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build version check app
        run: |
             echo "build CheckVersionPublished helper app"
             dotnet build .github/CheckVersionPublished/CheckVersionPublished.csproj -c Release -r linux-64 -o ./
      - name: run the version check app save result in environment variable
        run: |
             echo "run CheckVersionPublished helper app"
             echo "version_published=./CheckVersionPublished Sharpi/Sharpi.csproj" >> $GITHUB_ENV
      - name: authenticate then build, pack, publish main project package
        if: ${{ env.version_published }} == 0
        run: |
            echo "already exists"
            
