name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: authenticate, build, pack, publish
        run: |
             echo "build CheckVersionPublished helper app"
             dotnet build ../.github/CheckVersionPublished/CheckVersionPublished.csproj  
            
