name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
            
      - name: run the version check and save result in environment vars
        run: |
             echo "check package exists"
             dotnet run .github/CheckVersionPublished/CheckVersionPublished.csproj Sharpi/Sharpi.csproj
             #echo "version_published=(dotnet run .github/CheckVersionPublished/CheckVersionPublished.csproj Sharpi/Sharpi.csproj)" >> $GITHUB_ENV
      - name: authenticate then build, pack, publish main project package
        if: ${{ env.version_published }} == 0
        run: |
            echo "starting authenticate, build, pack; publish"
            
